### create
POST {{baseUrl}}
Content-Type: application/json

{
  "message": "Test dai"
}

### update
PUT {{baseUrl}}/51
Content-Type: application/json

{
  "message": "Test dai 5"
}

### delete

DELETE {{baseUrl}}/1

### read all
GET POST {{baseUrl}}

### delete all

DELETE POST {{baseUrl}}

